env:
  - TRAVIS=true
before_install:
  - sudo apt-get install libicu-dev -y
branches:
  only:
    - 'master'
rvm:
  - 1.9.3
  - 2.0.0
before_script:
  - "bundle install"
script: "bundle exec rake test"
