rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    # JRuby does not support C extensions on Travis
    - { rvm: jruby-18mode }
    - { rvm: jruby-19mode }
